from fastapi import FastAPI, File, UploadFile, HTTPException
from fastapi.middleware.cors import CORSMiddleware
from tensorflow.keras.models import load_model
from tensorflow.keras.preprocessing import image
import numpy as np
import io
from PIL import Image

app = FastAPI(title="Lung Cancer Prediction API")

# Allow CORS for all origins, required for frontend communication
app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)

# Load model locally
try:
    # Use the .h5 or .keras model generated by lung_cancer_prediction_final.py
    model = load_model("lung_cancer_model_final.h5")
except Exception as e:
    model = None
    print(f"Warning: Model not found at path lung_cancer_model_final.h5. Make sure you run the training script first. Error: {e}")

# Class labels (as derived from the training generator class indices)
# You may need to verify these labels match the ones from lung_cancer_prediction_final.py exactly
LABELS = ["adenocarcinoma", "large.cell.carcinoma", "normal", "squamous.cell.carcinoma"] 

IMAGE_SIZE = (224, 224)

@app.get("/")
def read_root():
    return {"status": "success", "message": "Lung Cancer Prediction API is running."}

@app.post("/predict")
async def predict_image(file: UploadFile = File(...)):
    if model is None:
        raise HTTPException(status_code=500, detail="Model file not loaded. Please train or provide the model first.")
    
    if not file.content_type.startswith("image/"):
        raise HTTPException(status_code=400, detail="Invalid file type. Please upload an image.")
    
    try:
        # Read image to PIL
        contents = await file.read()
        img = Image.open(io.BytesIO(contents)).convert("RGB")
        
        # Resize to match model input
        img = img.resize(IMAGE_SIZE)
        
        # Convert to array and scale
        img_array = image.img_to_array(img) / 255.0
        img_array = np.expand_dims(img_array, axis=0) # Shape: (1, 224, 224, 3)
        
        # Predict
        prediction = model.predict(img_array)
        class_idx = np.argmax(prediction[0])
        confidence = float(np.max(prediction[0]))
        
        predicted_class = LABELS[class_idx]
        
        return {
            "prediction": predicted_class,
            "confidence": confidence,
            "all_probabilities": {LABELS[i]: float(prediction[0][i]) for i in range(len(LABELS))}
        }
    except Exception as e:
        raise HTTPException(status_code=500, detail=str(e))

if __name__ == "__main__":
    import uvicorn
    # Make sure to run the application on port 8000
    uvicorn.run(app, host="0.0.0.0", port=8000)
